# Generated by Django 2.1.3 on 2019-07-07 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='默认用户', max_length=50, verbose_name='用户名')),
                ('pid', models.IntegerField(default=1, verbose_name='身份ID')),
                ('department', models.CharField(default='某部门', max_length=50, verbose_name='部门')),
                ('classification', models.CharField(default='技术岗', max_length=50, verbose_name='类别')),
                ('rank', models.CharField(default='1级', max_length=50, verbose_name='职级')),
                ('tel', models.IntegerField(default=10086, verbose_name='电话')),
                ('canteen', models.CharField(default='1号食堂', max_length=50, verbose_name='食堂')),
                ('pub_date', models.DateTimeField(verbose_name='创建实践')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='管理者')),
            ],
        ),
    ]
